spring:

  h2:
    console:
      enabled: true
      path: /h2-console

  messages:
    basename: messages, errors

  datasource:
    url: jdbc:h2:mem:test;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    #      none : db를 변경하지 않고 계속 사용하는 설정.
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션 // 글로벌 로딩 전략
        # 100 개 단위로 끊어서 가지고 오겠다는 뜻.
        highlight_sql: true
        use_sql_comments: true
    open-in-view: false

logging:
  level:
    org:
#      springframework:
#        jdbc: debug
      hibernate:
        SQL: debug
#        type: trace
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
        jdbc:
          bind:
            TRACE


server:
  error:
    whitelabel:
      enabled: false
    include-exception: false
    include-message: always
    include-stacktrace: never
    include-binding-errors: never

  servlet:
    session:
      tracking-modes=cookie: cookie
      timeout: 1800
